baseURL = "/"
languageCode = "en-us"
title = "Sinclair Intervention"
theme="archie"
copyright = "© Sinclair Interventions and Associates"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=false
	subtitle = "Sinclair Interventions and Associates contact jamessinclair.intervention@gmail.com"

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4
